spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/visadb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
  thymeleaf:
    cache: false
logging:
  level:
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
server:
  port: 8020
